const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('assets/app.js','utf8');
const css=fs.readFileSync('assets/style.css','utf8');
const html=fs.readFileSync('app.html','utf8');
const server=fs.readFileSync('server.js','utf8');
assert(css.includes('body.fullpage-unscaled{zoom:1;width:100%'));
assert(app.includes('function syncFullPageScale()'));
assert(app.includes("#bookingOverlay.open,#detailOverlay.open,#customerListOverlay.open"));
assert(app.includes(".app-view.workspace-fullpage.active"));
assert(app.includes('showViewWithResponsiveScale'));
assert(/assets\/app\.js\?v=7\.63\.\d+-/.test(html));
assert(/const RELEASE_NAME = 'v7\.63\.\d+-production'/.test(server));
console.log('v7.63.26 full-page scale regression: PASS');
