const fs=require('fs'),assert=require('assert');
const read=f=>fs.readFileSync(f,'utf8');
const server=read('server.js'),html=read('ocr-review-mockup.html'),ps=read('tools/ocr-scan-agent/scan-agent.ps1'),install=read('tools/ocr-scan-agent/install-agent.ps1'),cmd=read('tools/ocr-scan-agent/INSTALL-SCAN-AGENT.cmd');
assert(server.includes("const RELEASE_NAME = 'v7.63.49-production'"));
assert.strictEqual(read('VERSION.txt').trim(),'v7.63.49');
assert(server.includes("/downloads/healthcheck-scan-agent-v7.63.49.zip"));
assert(server.includes("staffPagePermissionRequired('ocrDocumentView')"));
assert(html.includes('id="installScanAgentBtn"'));
assert(html.includes('/downloads/healthcheck-scan-agent-v7.63.49.zip'));
assert(html.includes('TWAIN 32-bit เป็นหลัก'));
assert(ps.includes('NTwain.dll'));
assert(ps.includes('PreferNewDSM=$false'));
assert(ps.includes('CapFeederEnabled'));
assert(ps.includes('CapAutoFeed'));
assert(ps.includes('GetSources()'));
assert(ps.includes('SourceEnableMode]::NoUI'));
assert(ps.includes('scan-agent-wia.ps1'));
assert(install.includes('SysWOW64\\WindowsPowerShell'));
assert(install.includes('api.nuget.org/v3-flatcontainer/ntwain/3.7.6'));
assert(cmd.includes('install-agent.ps1'));
assert(fs.existsSync('tools/ocr-scan-agent/OCR-SCAN-AGENT-NO-ADMIN.zip'));
console.log('v7.63.49 TWAIN-first self-service Scan Agent regression passed');
