const fs=require('fs'),path=require('path'),assert=require('assert');
const root=__dirname;
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const current=read('VERSION.txt').trim().replace(/^v/,'').split('.').map(Number);
assert(current[0]>7 || (current[0]===7 && (current[1]>63 || (current[1]===63 && current[2]>=53))));
const pkg=require('./package.json').version.split('.').map(Number);
assert(pkg[0]>7 || (pkg[0]===7 && (pkg[1]>63 || (pkg[1]===63 && pkg[2]>=53))));
const server=read('server.js');
assert(/v7\.63\.(?:5[3-9]|[6-9]\d)-production/.test(server));
assert(server.includes('/downloads/healthcheck-scan-agent-v7.63.53.zip'));
const html=read('ocr-review-mockup.html');
assert(html.includes('v7.63.53 — OCR viewport-fit'));
assert(html.includes("'image/bmp'"));
assert(html.includes('grid-template-columns:minmax(210px,.62fr) minmax(300px,1fr) minmax(410px,1.35fr)'));
const go=read('tools/ocr-scan-agent/src/main.go');
assert(go.includes('strings.EqualFold(strings.TrimSpace(s.name()),"Scan")'));
assert(go.includes('DAT_STATUS'));
assert(go.includes('DAT_IMAGEMEMXFER'));
assert(go.includes('TWSX_MEMORY'));
assert(go.includes('isWIAWrapper'));
assert(go.includes('ระบบจะไม่สลับไป WIA อัตโนมัติ'));
assert(fs.existsSync(path.join(root,'tools/ocr-scan-agent/HealthCheckTwainAgent.exe')));
console.log('v7.63.53 TWAIN Memory + OCR viewport fit regression passed');
