const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const install=read('tools/install.ps1');
const gui=read('tools/universal-installer-gui.ps1');
const worker=read('tools/installer-worker.ps1');
const deploy=read('tools/deploy-environment.ps1');
const server=read('server.js');
assert(install.includes('Existing application database credential verified'));
assert(install.includes('Administrator password is not required for this upgrade'));
assert(install.includes('$appUpgradeConnected'));
assert(install.includes("$backupUser = [string]$existingConfig.PGUSER"));
assert(install.includes('DPAPI-MACHINE:'));
assert(gui.includes('DPAPI-MACHINE:'));
assert(gui.includes('Usually optional for upgrades; required for fresh install'));
assert(worker.includes("$version='v7.62.55'"));
assert(deploy.includes('$prefix-source-before-v7.62.55'));
assert(server.includes("v7.62.55-rc-compact-gui-installer"));
console.log('v7.62.55 upgrade-without-postgres-admin + credential transport regression PASS');
