const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=__dirname;
const server=fs.readFileSync(path.join(root,'server.js'),'utf8');
const html=fs.readFileSync(path.join(root,'ocr-review-mockup.html'),'utf8');
const install=fs.readFileSync(path.join(root,'tools/ocr-scan-agent/install-agent.ps1'),'utf8');
const cmd=fs.readFileSync(path.join(root,'tools/ocr-scan-agent/INSTALL-SCAN-AGENT.cmd'),'utf8');
assert(server.includes("v7.63.52-production"));
assert(server.includes('/downloads/healthcheck-scan-agent-v7.63.52.zip'));
assert(html.includes('Scan Agent v7.63.52 Prebuilt'));
assert(html.includes('ไม่ Compile ที่เครื่อง User'));
assert(fs.existsSync(path.join(root,'tools/ocr-scan-agent/HealthCheckTwainAgent.exe')));
assert(!install.includes('csc.exe'));
assert(!install.includes('Compiling'));
assert(!install.includes('Invoke-WebRequest'));
assert(!install.includes('System.Net.WebClient'));
assert(!install.includes('csc.exe'));
assert(!install.includes('& $csc'));
assert(install.includes("HealthCheckTwainAgent.exe"));
assert(install.includes('Copy-Item $exeSource'));
assert(cmd.includes('Prebuilt TWAIN x86'));
console.log('v7.63.52 prebuilt TWAIN installer regression passed');
