param(
 [Parameter(Mandatory=$true)][string]$PackagePath,
 [Parameter(Mandatory=$true)][string]$AppRoot,
 [Parameter(Mandatory=$true)][int]$ServerPid,
 [Parameter(Mandatory=$true)][string]$CurrentVersion,
 [string]$StatusPath=''
)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$updateDir=Join-Path $AppRoot 'updates';if(-not $StatusPath){$StatusPath=Join-Path $updateDir 'update-status.json'}
$workRoot=Join-Path $env:TEMP 'HealthCheck-Updater';New-Item -ItemType Directory -Path $workRoot,$updateDir -Force|Out-Null
$logPath=Join-Path $workRoot ("in-app-update-{0}.log" -f (Get-Date -Format 'yyyyMMdd-HHmmss'))
function Set-Status([string]$phase,[string]$message,[hashtable]$extra=@{}){$obj=[ordered]@{phase=$phase;message=$message;updatedAt=(Get-Date).ToString('o');logPath=$logPath};foreach($k in $extra.Keys){$obj[$k]=$extra[$k]};$tmp="$StatusPath.tmp-$PID";$obj|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $tmp -Encoding UTF8;Move-Item -LiteralPath $tmp -Destination $StatusPath -Force;"[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] [$phase] $message"|Add-Content -LiteralPath $logPath -Encoding UTF8}
function Read-Env([string]$path){$map=@{};Get-Content -LiteralPath $path|ForEach-Object{if($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$'){$map[$matches[1]]=$matches[2].Trim().Trim('"').Trim("'")}};return $map}
function Find-Exe([string]$name,[string[]]$fallbacks){$cmd=Get-Command $name -ErrorAction SilentlyContinue;if($cmd){return $cmd.Source};foreach($f in $fallbacks){if(Test-Path -LiteralPath $f){return $f}};return $null}
function Run-Proc([string]$file,[string[]]$args,[string]$cwd=''){$out=Join-Path $workRoot ("out-$PID-$([guid]::NewGuid().ToString('N')).log");$err=Join-Path $workRoot ("err-$PID-$([guid]::NewGuid().ToString('N')).log");$params=@{FilePath=$file;ArgumentList=$args;Wait=$true;PassThru=$true;WindowStyle='Hidden';RedirectStandardOutput=$out;RedirectStandardError=$err};if($cwd){$params.WorkingDirectory=$cwd};$proc=Start-Process @params;if(Test-Path $out){Get-Content $out|Add-Content $logPath};if(Test-Path $err){Get-Content $err|Add-Content $logPath};Remove-Item $out,$err -Force -ErrorAction SilentlyContinue;if($proc.ExitCode -ne 0){throw "Process failed ($($proc.ExitCode)): $file"}}
function Copy-Tree([string]$source,[string]$dest,[switch]$Mirror){New-Item -ItemType Directory -Path $dest -Force|Out-Null;$mode=$(if($Mirror){'/MIR'}else{'/E'});$args=@($source,$dest,$mode,'/R:2','/W:1','/NFL','/NDL','/NJH','/NJS','/NP','/XD','node_modules','logs','backups','updates','.git','/XF','.env');$p=Start-Process -FilePath 'robocopy.exe' -ArgumentList $args -Wait -PassThru -WindowStyle Hidden;if($p.ExitCode -gt 7){throw "robocopy failed code=$($p.ExitCode)"}}
function Start-App([string]$root,[string]$expectedVersion){$node=Find-Exe 'node.exe' @('C:\Program Files\nodejs\node.exe');if(-not $node){throw 'Node.js not found'};$server=Join-Path $root 'server.js';Start-Process -FilePath $node -ArgumentList @($server) -WorkingDirectory $root -WindowStyle Hidden|Out-Null;for($i=0;$i -lt 60;$i++){Start-Sleep -Seconds 1;try{$v=Invoke-RestMethod -Uri 'http://127.0.0.1:3000/api/version' -TimeoutSec 2;if($v.environment -eq 'production' -and [string]$v.version -eq $expectedVersion){return $true}}catch{}};return $false}
$backup='';$newVersion='';$dbBackup='';$failedPhase='PRECHECK'
try{
 Set-Status 'PRECHECK' 'ตรวจสอบแพ็กเกจ Production';if(-not(Test-Path $PackagePath)){throw 'Update package not found'};if(-not(Test-Path (Join-Path $AppRoot '.env'))){throw '.env not found'}
 $stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$work=Join-Path $workRoot "work-$stamp";$extract=Join-Path $work 'extract';$backup=Join-Path $work 'rollback-source';New-Item -ItemType Directory -Path $extract,$backup -Force|Out-Null;Expand-Archive -LiteralPath $PackagePath -DestinationPath $extract -Force
 $candidate=Get-ChildItem -LiteralPath $extract -Directory -Recurse|Where-Object{Test-Path(Join-Path $_.FullName 'server.js')}|Select-Object -First 1;if(-not $candidate -and(Test-Path(Join-Path $extract 'server.js'))){$candidate=Get-Item $extract};if(-not $candidate){throw 'ไม่พบ server.js ใน Update Package'}
 $line=Select-String -LiteralPath (Join-Path $candidate.FullName 'server.js') -Pattern "RELEASE_NAME\s*=\s*'v([0-9.]+)-production'"|Select-Object -First 1;if(-not $line){throw 'แพ็กเกจนี้ไม่ใช่ Production release'};$newVersion='v'+$line.Matches[0].Groups[1].Value
 if([version]$newVersion.TrimStart('v') -le [version]$CurrentVersion.TrimStart('v')){throw "แพ็กเกจ $newVersion ต้องใหม่กว่า $CurrentVersion"}
 $failedPhase='BACKUP';Set-Status 'BACKUP' "สำรอง Source และ Database ก่อนอัปเดตเป็น $newVersion" @{targetVersion=$newVersion};Copy-Tree $AppRoot $backup
 $envMap=Read-Env (Join-Path $AppRoot '.env');$pgDump=Find-Exe 'pg_dump.exe' @('C:\Program Files\PostgreSQL\17\bin\pg_dump.exe','C:\Program Files\PostgreSQL\16\bin\pg_dump.exe','C:\Program Files\PostgreSQL\15\bin\pg_dump.exe');if(-not $pgDump){throw 'pg_dump.exe not found'};$env:PGPASSWORD=[string]$envMap.PGPASSWORD;$dbBackup=Join-Path $updateDir ("database-before-{0}-{1}.backup" -f $newVersion,$stamp);Run-Proc $pgDump @('-h',[string]$envMap.PGHOST,'-p',[string]$envMap.PGPORT,'-U',[string]$envMap.PGUSER,'-d',[string]$envMap.PGDATABASE,'-F','c','-f',$dbBackup)
 $failedPhase='STOP';Set-Status 'STOP' 'หยุด Production server';Stop-Process -Id $ServerPid -Force -ErrorAction SilentlyContinue;Start-Sleep -Seconds 2
 $failedPhase='DEPLOY';Set-Status 'DEPLOY' "ติดตั้ง $newVersion";Copy-Tree $candidate.FullName $AppRoot -Mirror;$npm=Find-Exe 'npm.cmd' @('C:\Program Files\nodejs\npm.cmd');if($npm){Run-Proc $npm @('ci','--omit=dev','--no-audit','--no-fund') $AppRoot}
 $failedPhase='MIGRATE';Set-Status 'MIGRATE' 'รัน Database migrations';$psql=Find-Exe 'psql.exe' @('C:\Program Files\PostgreSQL\17\bin\psql.exe','C:\Program Files\PostgreSQL\16\bin\psql.exe','C:\Program Files\PostgreSQL\15\bin\psql.exe');if(-not $psql){throw 'psql.exe not found'};Get-ChildItem (Join-Path $AppRoot 'migrations') -Filter '*.up.sql'|Sort-Object Name|ForEach-Object{Run-Proc $psql @('-h',[string]$envMap.PGHOST,'-p',[string]$envMap.PGPORT,'-U',[string]$envMap.PGUSER,'-d',[string]$envMap.PGDATABASE,'-v','ON_ERROR_STOP=1','-f',$_.FullName)}
 $failedPhase='START';Set-Status 'START' 'เปิด Production server เวอร์ชันใหม่';if(-not(Start-App $AppRoot $newVersion)){throw "เปิด $newVersion ไม่สำเร็จ"}
 $failedPhase='HEALTH';Set-Status 'HEALTH' 'ตรวจสอบ Version และ Database Health';$health=$null;for($i=0;$i -lt 20;$i++){try{$health=Invoke-RestMethod -Uri 'http://127.0.0.1:3000/api/system/health' -TimeoutSec 3;if($health.database.ok -eq $true){break}}catch{};Start-Sleep -Seconds 1};if(-not $health -or $health.database.ok -ne $true){throw 'Database health check ไม่ผ่าน'}
 Set-Status 'SUCCESS' "อัปเดต Production สำเร็จเป็น $newVersion" @{version=$newVersion;databaseBackup=$dbBackup}
}catch{
 $msg=$_.Exception.Message;Set-Status 'ROLLBACK' "ขั้น $failedPhase ล้มเหลว กำลังคืน Source เดิม: $msg" @{failedPhase=$failedPhase};try{if($backup -and(Test-Path $backup)){Copy-Tree $backup $AppRoot -Mirror;Start-App $AppRoot $CurrentVersion|Out-Null;Set-Status 'FAILED' "อัปเดตไม่สำเร็จ คืน Source เดิมแล้ว: $msg" @{rolledBack=$true;failedPhase=$failedPhase}}else{Set-Status 'FAILED' "อัปเดตไม่สำเร็จ: $msg" @{rolledBack=$false;failedPhase=$failedPhase}}}catch{Set-Status 'FAILED' "อัปเดตและ rollback ไม่สำเร็จ: $msg / $($_.Exception.Message)" @{rolledBack=$false;failedPhase=$failedPhase}}
}
